name: PR Preview (Jekyll → GitHub Pages)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .         # or your docs/ dir
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages (PR preview)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Preview deployments are supported via Marketplace actions;
          # deploy-pages v4 itself exposes a "preview" input but it’s not generally available.
          # See notes and alt actions below.
          artifact_name: github-pages
